FROM node:24-alpine

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY --chown=node:node . .

USER node
EXPOSE 3000

ENTRYPOINT ["npx", "tsx", "--inspect-brk=0.0.0.0:9229", "--env-file=.env", "src/index"]
